### ISSUE TITLE
Node crashes without showing error message

### ISSUE THREAD

**Issue by ivanpauno** [ros2/sros2#116]
## Bug report

**Required Info:**

- Operating System:
  - Windows Server 2019 (datacenter)
- Installation type:
  - Binaries
- Version or commit hash:
  - Fat archive from https://ci.ros2.org/job/packaging_windows/1388/
- DDS implementation:
  - FastRTPS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Follow https://github.com/ros2/sros2/blob/master/SROS2_Windows.md tutorial.
After having configuring the command prompt for use security (with or without `Authentication`), run any other example not related to talker/listener. e.g.:
```bat
ros2 run intra_process_demo cyclic_pipeline
```

#### Expected behavior
It should show a nice error.

#### Actual behavior
It's finished without saying nothing.

#### Additional information

Doing `echo %errorlevel%` returns `-1`.
I don't know if this is the known behavior of it's a bug.
If it's known, it would be nice to at least show an error message.

**Comment by mikaelarguedas** [comment]
> After having configuring the command prompt for use security (with or without Authentication), run any other example not related to talker/listener. e.g.:

Does this mean that the environment variable `ROS_SECURITY_ENABLE` is set to `true` and `ROS_SECURITY_STRATEGY` to `Enforce` in the command prompt used?

> I don't know if this is the known behavior of it's a bug.
If it's known, it would be nice to at least show an error message.

It is expected behavior that a node without credential fails to be created if the prompt is configured to use SROS2.
It should print an error though, something similar to (error message copied from https://ci.ros2.org/view/nightly/job/nightly_win_deb/1271/consoleFull#console-section-771):
```
'SECURITY ERROR: directory garbage\publisher does not exist. Lookup strategy: MATCH_EXACT, at C:\J\workspace\nightly_win_deb\ws\src\ros2\rcl\rcl\src\rcl\security_directory.c:256'
```

Does `ros2 run demo_nodes_cpp talker` work?
Does `ros2 run demo_nodes_cpp talker __node:=not_talker` fail? If yes does it fail with or without an error message?

**Comment by ivanpauno** [comment]
> Does this mean that the environment variable `ROS_SECURITY_ENABLE` is set to `true` and `ROS_SECURITY_STRATEGY` to `Enforce` in the command prompt used?

Yes.
 
> It is expected behavior that a node without credential fails to be created if the prompt is configured to use SROS2.
> It should print an error though, something similar to (error message copied from https://ci.ros2.org/view/nightly/job/nightly_win_deb/1271/consoleFull#console-section-771):
>
> ```
> 'SECURITY ERROR: directory garbage\publisher does not exist. Lookup strategy: MATCH_EXACT, at C:\J\workspace\nightly_win_deb\ws\src\ros2\rcl\rcl\src\rcl\security_directory.c:256'
> ```

That error message didn't appear.
 
> Does `ros2 run demo_nodes_cpp talker` work?
> Does `ros2 run demo_nodes_cpp talker __node:=not_talker` fail? If yes does it fail with or without an error message?

Yes, that one failed with an error message.

I will try to reproduce this error in linux too, to check if it happens or not.

**Comment by ivanpauno** [comment]
> I will try to reproduce this error in linux too, to check if it happens or not.

Can't reproduce it on Linux, I see the error message you're mentioning in that case.

On Windows, I only see that error message when doing a remapping on talker or listener demos. But when running any other executable (intra_process_demo cyclic_pipeline, demo_nodes_cpp add_two_ints_server, demo_nodes_cpp parameter_blackboard), it crashes without printing an error message.

**Comment by mikaelarguedas** [comment]
> On Windows, I only see that error message when doing a remapping on talker or listener demos. But when running any other executable (intra_process_demo cyclic_pipeline, demo_nodes_cpp add_two_ints_server, demo_nodes_cpp parameter_blackboard), it crashes without printing an error message.

hmmm that is odd, and definitely not expected behavior. I don't have the ability to test on Windows at the moment.

Maybe you will get more hints of where it's crashing by enabling more logging? e.g. if you run
```
ros2 run demo_nodes_py talker_qos __log_level:=debug
```

Bypassing Python and running you executable directly may also help getting more information
e.g. `install\lib\demo_nodes_cpp\add_two_ints_server`


Is it also crashing if you set `ROS_SECURITY_STRATEGY` to `permissive`? (expected behavior is *no crash*)

**Comment by ruffsl** [comment]
> Expected behavior
> It should show a nice error.

I guess you clarified to @mikaelarguedas that you did set `ROS_SECURITY_ENABLE=true` for all nodes, include the not related/provisioned example node; though as an FYI if you enable `ROS_SECURITY_ENABLE`  for the talker/listener, but not for the non-related node, then you may not necessarily encounter any reported errors. Event warnings when security setting are mismatched may be dependent upon the DDS vendor logging behavior or discovery security setting in the secure dds governance file.

> when doing a remapping on talker or listener demos

What do you mean by remapping? If you remap/change the ros2 topic/service names, you'd need to update the DDS topic permission accordingly.

**Comment by ivanpauno** [comment]
@ruffsl I did exactly the same steps in windows and linux, and the behavior is different.
I will detail them here:
- Install ros2.
  - In windows, I installed the fat archive (https://ci.ros2.org/job/packaging_windows/1388/).
  - In linux, I installed from source and built using `--cmake-args -DSECURITY=ON`.

In a new terminal/command-prompt:
- Followed `Generating a keystore, keys and certificates` subsection of the tutorial of the corresponding OS.
- Followed `Define the SROS2 environment variables` subsection of the tutorial of the corresponding OS.
- Run `ros2 run demo_nodes_py talker`. I see a message saying that security key was found (or sth similar), and I see the publisher starts working. Then `cntrl+c` it.
- Run  `ros2 run demo_nodes_py talker __node:=not_talker`. I see the error message, as described in the tutorial (both on windows and linux).
- Run `ros2 run intra_process_demo cyclic_pipeline` or any of the other executables I mentioned above. I see an error message on linux, but on Windows it just crushes without showing an error message.

All the `ros2 run` commands described above where executed in the same terminal/command-prompt, with the same env variables.
In both cases I'm using FastRTPS.

@mikaelarguedas I will later try to reproduce that cases and answer.

**Comment by ivanpauno** [comment]
> Maybe you will get more hints of where it's crashing by enabling more logging? e.g. if you run
> 
> ```
> ros2 run demo_nodes_py talker_qos __log_level:=debug
> ```

Running `ros2 run demo_nodes_cpp parameter_blackboard __log_level:=debug` results in:

```
[DEBUG] [rclcpp]: signal handler installed
[DEBUG] [rclcpp]: deferred_signal_handler(): waiting for SIGINT or uninstall
[DEBUG] [rcl]: Initializing node 'parameter_blackboard' in namespace ''
[DEBUG] [rcl]: Using domain ID of '0'
[DEBUG] [rcl]: Using security: true
``` 

And then it crashes.

> Bypassing Python and running you executable directly may also help getting more information
> e.g. `install\lib\demo_nodes_cpp\add_two_ints_server`

I ran `add_two_ints_client.exe` example using `devenv /DebugExe`
This is the exception being thrown:
```
Unhandled exception at 0x00007FFA182D9129 in add_two_ints_client.exe: Microsoft C++ exception: rclcpp::exceptions::RCLError at memory location 0x0000009CC74F98C0.
```

> Is it also crashing if you set `ROS_SECURITY_STRATEGY` to `permissive`? (expected behavior is _no crash_)

No, it doesn't crash.

----

Extra note: I realized that the wrong behavior is only with cpp executables. I see the expected error with python executables. For example, demo_nodes_py add_two_ints_service output:

```
Traceback (most recent call last):
  File "c:\dev\fat-archive-ros2\lib\demo_nodes_py\add_two_ints_server-script.py", line 11, in <module>
    load_entry_point('demo-nodes-py==0.7.1', 'console_scripts', 'add_two_ints_server')()
  File "c:\dev\fat-archive-ros2\Lib\site-packages\demo_nodes_py\services\add_two_ints_server.py", line 37, in main
    node = AddTwoIntsServer()
  File "c:\dev\fat-archive-ros2\Lib\site-packages\demo_nodes_py\services\add_two_ints_server.py", line 24, in __init__
    super().__init__('add_two_ints_server')
  File "c:\dev\fat-archive-ros2\Lib\site-packages\rclpy\node.py", line 152, in __init__
    node_name, namespace, self._context.handle, cli_args, use_global_arguments))
RuntimeError: Unknown error creating node: SECURITY ERROR: directory c:\dev\fat-archive-ros2\sros2_demo/demo_keys\add_two_ints_server does not exist. Lookup strategy: MATCH_EXACT, at C:\J\workspace\packaging_windows\ws\src\ros2\rcl\rcl\src\rcl\security_directory.c:256
```
