### ISSUE TITLE
SROS2 fails to use the DOMAIN_ID

### ISSUE THREAD

**Issue by AlexisTM** [ros2/sros2#169]
# ~Bug report~ The error message is not explicit enough 

Nodes fails to run with security enabled using **non-zero** DOMAIN_ID.

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- Version or commit hash:
  - ros-dashing-sros2/bionic,now 0.7.1-1bionic.20191016.193121 amd64 [installed]
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp and rclpy

#### Steps to reproduce issue

Generate security and start a node with a DOMAIN ID

```bash
cd ~
mkdir -p store
ros2 security create_keystore store
ros2 security create_key store /talker
export ROS_SECURITY_ROOT_DIRECTORY=~/store
export ROS_SECURITY_ENABLE=true
export ROS_SECURITY_STRATEGY=Enforce
export ROS_DOMAIN_ID=10
ros2 run demo_nodes_cpp talker
# As well as the python node
ros2 run demo_nodes_py talker
```

#### Expected behavior

The node starts with a different multicast port computed from the ROS_DOMAIN_ID value.

#### Actual behavior

The **rclcpp** node crashes with non zero DOMAIN_ID.

```log
[INFO] [rcl]: Found security directory: /home/alexis/store/talker
2019-11-05 11:30:09.008 [SECURITY Error] Error checking creation of local writer 93.eb.4b.d1.65.cd.79.ea.c1.e2.f1.59|0.0.1.3 (Not found topic access rule for topic rt/rosout (/tmp/binarydeb/ros-dashing-fastrtps-1.8.2/src/cpp/security/accesscontrol/Permissions.cpp:1065))
 -> Function register_local_writer
2019-11-05 11:30:09.008 [PARTICIPANT Error] Problem creating associated Writer -> Function createPublisher
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to initialize rcl node: create_publisher() could not create publisher, at /tmp/binarydeb/ros-dashing-rmw-fastrtps-cpp-0.7.6/src/rmw_publisher.cpp:175, at /tmp/binarydeb/ros-dashing-rcl-0.7.7/src/rcl/publisher.c:171
```

The **rclpy** node crashes with non zero DOMAIN_ID.

```log
[INFO] [rcl]: Found security directory: /home/alexis/store/talker
2019-11-05 11:32:12.663 [SECURITY Error] Error checking creation of local writer 93.eb.4b.d1.65.cd.e4.19.eb.8e.c3.36|0.0.1.3 (Not found topic access rule for topic rt/rosout (/tmp/binarydeb/ros-dashing-fastrtps-1.8.2/src/cpp/security/accesscontrol/Permissions.cpp:1065))
 -> Function register_local_writer
2019-11-05 11:32:12.663 [PARTICIPANT Error] Problem creating associated Writer -> Function createPublisher
Traceback (most recent call last):
  File "/opt/ros/dashing/lib/demo_nodes_py/talker", line 11, in <module>
    load_entry_point('demo-nodes-py==0.7.9', 'console_scripts', 'talker')()
  File "/opt/ros/dashing/lib/python3.6/site-packages/demo_nodes_py/topics/talker.py", line 41, in main
    node = Talker()
  File "/opt/ros/dashing/lib/python3.6/site-packages/demo_nodes_py/topics/talker.py", line 24, in __init__
    super().__init__('talker')
  File "/opt/ros/dashing/lib/python3.6/site-packages/rclpy/node.py", line 152, in __init__
    node_name, namespace, self._context.handle, cli_args, use_global_arguments))
RuntimeError: Unknown error creating node: create_publisher() could not create publisher, at /tmp/binarydeb/ros-dashing-rmw-fastrtps-cpp-0.7.6/src/rmw_publisher.cpp:175, at /tmp/binarydeb/ros-dashing-rcl-0.7.7/src/rcl/publisher.c:171
```

# Fix

The security keys depend on the DOMAIN_ID. Thus ROS_DOMAIN_ID has to be defined before creating the keys.

```bash
cd ~
mkdir -p store
export ROS_SECURITY_ROOT_DIRECTORY=~/store
export ROS_SECURITY_ENABLE=true
export ROS_SECURITY_STRATEGY=Enforce
export ROS_DOMAIN_ID=10
ros2 security create_keystore store
ros2 security create_key store /talker
ros2 run demo_nodes_cpp talker
# As well as the python node
ros2 run demo_nodes_py talker
```

**Comment by mikaelarguedas** [comment]
The generated security material is domain ID dependant. This is on purpose as in most cases you don't want your security material to be usable on all domain IDs.

You should be able to generate security material for a specific domain ID by setting "ROS_DOMAIN_ID" before running the `ros2 security` commands. If non specified, 0 will be used instead.

Ideally the error message would be more specific than "rule x could not be found in allow rule" but this error message comes from the DDS implementation and the ROS part of the code doesn't know why the creation failed so I don't see an easy way to improve it.

**Comment by AlexisTM** [comment]
Thanks! This was indeed the issue;

Closing.
