### ISSUE TITLE
check_openssl_version fails despite openssl being installed

### ISSUE THREAD

**Issue by sloretz** [ros2/sros2#22]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - http://ci.ros2.org/view/packaging/job/packaging_windows/728/artifact/ws/ros2-package-windows-AMD64.zip
- Version or commit hash:
  - def304b4270b6b935b7d6fbbf7671634c2532452
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclp

#### Steps to reproduce issue

1. Follow instructions here to install openssl https://github.com/ros2/ros2/wiki/Windows-Install-Binary
2. Run command from this tutorial https://github.com/ros2/sros2/blob/master/SROS2_Windows.md
    - `ros2 security create_keystore demo_keys`

#### Expected behavior
No traceback

#### Actual behavior

```
C:\dev\ros2\sros2_demo>ros2 security create_keystore demo_keys
Namespace(ROOT='demo_keys', _command=<sros2.command.security.SecurityCommand object at 0x0000004348FEE9E8>, _verb=<sros2.verb.create_keystore.CreateKeystoreVerb object at 0x000000434935B940>, **{' command': 'security', ' verb': 'create_keystore'})
directory already exists: demo_keys
found CA conf file, not writing a new one!
creating ECDSA param file: demo_keys\ecdsaparam
Traceback (most recent call last):
  File "C:\dev\ros2\Scripts\ros2-script.py", line 11, in <module>
    load_entry_point('ros2cli==0.0.0', 'console_scripts', 'ros2')()
  File "C:\dev\ros2\Lib\site-packages\ros2cli\cli.py", line 64, in main
    rc = extension.main(parser=parser, args=args)
  File "C:\dev\ros2\Lib\site-packages\sros2\command\security.py", line 34, in main
    return extension.main(args=args)
  File "C:\dev\ros2\Lib\site-packages\sros2\verb\create_keystore.py", line 33, in main
    success = create_keystore(args)
  File "C:\dev\ros2\Lib\site-packages\sros2\api\__init__.py", line 184, in create_keystore
    create_ecdsa_param_file(ecdsa_param_path)
  File "C:\dev\ros2\Lib\site-packages\sros2\api\__init__.py", line 112, in create_ecdsa_param_file
    check_openssl_version(openssl_executable)
  File "C:\dev\ros2\Lib\site-packages\sros2\api\__init__.py", line 39, in check_openssl_version
    stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "C:\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Python36\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

#### Additional information

```
C:\dev\ros2\sros2_demo>openssl
'openssl' is not recognized as an internal or external command,
operable program or batch file.

C:\dev\ros2\sros2_demo>start openssl

C:\dev\ros2\sros2_demo>where openssl
C:\OpenSSL-Win64\bin\openssl.exe
```

```
C:\dev\ros2\sros2_demo>echo %PATH%
C:\dev\ros2\Scripts;C:\dev\ros2\bin;C:\Python36\Scripts\;C:\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\dev\opencv-2.4.13.2-vc14.VS2015;C:\ProgramData\chocolatey\bin;C:\ProgramData\chocolatey\lib\tinyxml2\lib;C:\OpenSSL-Win64\bin\

C:\dev\ros2\sros2_demo>echo %OPENSSL_CONF%
C:\OpenSSL-Win64\bin\openssl.cfg
```

**Comment by sloretz** [comment]
Thanks to @mikaelarguedas for figuring out that a trailing space in the %PATH% variable causes this behavior! Removing the trailing space fixes the issue.
