### ISSUE TITLE
👨‍🌾 test_generate_policy_no_nodes failed on Windows (Debug)

### ISSUE THREAD

**Issue by caguero** [ros2/sros2#264]
## Bug report

**Required Info:**

- Operating System:
  - Windows
- Installation type:
  - Source

#### Steps to reproduce issue

`test_generate_policy_no_nodes` failed on CI [here](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1994/).

#### Expected behavior

The test should pass.

#### Actual behavior

The test fails with the following message:

```
==================================================================================================================================================================================================================================
FAIL: test_generate_policy_no_nodes.TestSROS2GeneratePolicyVerbWithNoNodes.test_generate_policy_no_policy_file[rmw_cyclonedds_cpp, True]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ci\ws\src\ros2\sros2\sros2\test\sros2\commands\security\verbs\test_generate_policy_no_nodes.py", line 63, in test_generate_policy_no_policy_file
    assert gen_command.wait_for_shutdown(timeout=2)
AssertionError: assert False
 +  where False = <bound method ProcessProxy.wait_for_shutdown of <launch_testing.tools.process.ProcessProxy object at 0x000001C7C07643C0>>(timeout=2)
 +    where <bound method ProcessProxy.wait_for_shutdown of <launch_testing.tools.process.ProcessProxy object at 0x000001C7C07643C0>> = <launch_testing.tools.process.ProcessProxy object at 0x000001C7C07643C0>.wait_for_shutdown


==================================================================================================================================================================================================================================
FAIL: test_generate_policy_no_nodes.TestSROS2GeneratePolicyVerbWithNoNodes.test_generate_policy_no_policy_file[rmw_fastrtps_cpp, False]
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ci\ws\src\ros2\sros2\sros2\test\sros2\commands\security\verbs\test_generate_policy_no_nodes.py", line 63, in test_generate_policy_no_policy_file
    assert gen_command.wait_for_shutdown(timeout=2)
AssertionError: assert False
 +  where False = <bound method ProcessProxy.wait_for_shutdown of <launch_testing.tools.process.ProcessProxy object at 0x000001C7C1A13730>>(timeout=2)
 +    where <bound method ProcessProxy.wait_for_shutdown of <launch_testing.tools.process.ProcessProxy object at 0x000001C7C1A13730>> = <launch_testing.tools.process.ProcessProxy object at 0x000001C7C1A13730>.wait_for_shutdown
```

**Comment by ruffsl** [comment]
Does anyone else have a Windows license and system install to be able to reproduce this locally? I no longer have access to a Windows 10 workstation after graduating from my university.
