### ISSUE TITLE
Failure to create participant using rmw_connext_cpp

### ISSUE THREAD

**Issue by sloretz** [ros2/sros2#59]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - binaries
- Version or commit hash:
  - https://ci.ros2.org/view/packaging/job/packaging_windows/1043/
- DDS implementation:
  - RTI Connext
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```bat
md C:\dev\sros2_demo
cd C:\dev\sros2_demo
set RANDFILE=C:\dev\sros2_demo\.rnd
ros2 security create_keystore demo_keys
ros2 security create_key demo_keys talker
ros2 security create_key demo_keys listener
set ROS_SECURITY_ROOT_DIRECTORY=%cd%/demo_keys
set ROS_SECURITY_ENABLE=true
set ROS_SECURITY_STRATEGY=Enforce
ros2 run demo_nodes_cpp talker
```

#### Expected behavior

talker should begin publishing

#### Actual behavior

```
>ros2 run demo_nodes_py talker
RTI Data Distribution Service Evaluation License issued to OSRF (OSRF01) dthomas@osrfoundation.org For non-production use only.
Expires on 5-Nov-2018 See www.rti.com for more information.
[CREATE Participant]RTIOsapiLibrary_open:error opening library nddssecurity.dll
[CREATE Participant]DDS_DomainParticipantTrustPlugins_initialize:!failed to load library
[CREATE Participant]DDS_DomainParticipant_createI:!create builtin trust plugins support
[CREATE Participant]DDS_DomainParticipantFactory_create_participant_disabledI:!create participant
DDSDomainParticipant_impl::create_disabledI:!create participant
DDSDomainParticipant_impl::createI:!create participant
DomainParticipantFactory_impl::create_participant():!create failure creating participant
Traceback (most recent call last):
  File "C:\dev\ros2-windows\lib\demo_nodes_py\talker-script.py", line 11, in <module>
    load_entry_point('demo-nodes-py==0.4.0', 'console_scripts', 'talker')()
  File "C:\dev\ros2-windows\Lib\site-packages\demo_nodes_py\topics\talker.py", line 46, in main
    node = Talker()
  File "C:\dev\ros2-windows\Lib\site-packages\demo_nodes_py\topics\talker.py", line 26, in __init__
    super().__init__('talker')
  File "C:\dev\ros2-windows\Lib\site-packages\rclpy\node.py", line 69, in __init__
    node_name, namespace, cli_args, use_global_arguments)
RuntimeError: Unknown error creating node: failed to create participant, at C:\J\workspace\packaging_windows\ws\src\ros2\rmw_connext\rmw_connext_shared_cpp\src\node.cpp:255, at C:\J\workspace\packaging_windows\ws\src\ros2\rcl\rcl\src\rcl\node.c:336
```

#### Additional information
Found while testing https://github.com/ros2/sros2/blob/master/SROS2_Windows.md

I'm not sure if security with connext is supposed to work on windows. The cell was originally grey'd out on the sheet, but the tutorial itself does mention setting `RMW_IMPLEMENTATION` to `rmw_connext_cpp`.

**Comment by dhood** [comment]
To use security with connext you have to install the security plugin through rti's launcher (at least that's necessary on osx and linux), I suspect is the reason it's having issues. (The error message for a C++ node might allude to this)

**Comment by sloretz** [comment]
Thanks @dhood, installing the security plugin resolved the issue
